<option style="color:white;" value="1">Level 1</option>
<option style="color:white;" value="2">Level 2</option>
<option style="color:white;" value="3">Level 3</option>
<option style="color:white;" value="4">Level 4</option>
<option style="color:white;" value="5">Level 5</option>
<option style="color:white;" value="6">Level 6</option>
<option style="color:white;" value="7">Level 7</option>
<option style="color:white;" value="8">Level 8</option>
<option style="color:white;" value="9">Level 9</option>
<option style="color:white;" value="10">Level 10</option>
<option style="color:white;" value="11">Level 11</option>
<option style="color:white;" value="12">Level 12</option>
<option style="color:white;" value="13">Level 13</option>
<option style="color:white;" value="14">Level 14</option>
<option style="color:white;" value="15">Level 15</option>
<option style="color:white;" value="16">Level 16</option>
<option style="color:white;" value="17">Level 17</option>
<option style="color:white;" value="18">Level 18</option>
<option style="color:white;" value="19">Level 19</option>
<option style="color:white;" value="20">Level 20</option>
<option style="color:white;" value="21">Level 21</option>
<option style="color:white;" value="22">Level 22</option>
<option style="color:white;" value="23">Level 23</option>
<option style="color:white;" value="24">Level 24</option>
<option style="color:white;" value="25">Level 25</option>
<option style="color:white;" value="26">Level 26</option>
<option style="color:white;" value="27">Level 27</option>
<option style="color:white;" value="28">Level 28</option>
<option style="color:white;" value="29">Level 29</option>
<option style="color:white;" value="30">Level 30</option>
<option style="color:white;" value="31">Level 31</option>
<option style="color:white;" value="32">Level 32</option>
<option style="color:white;" value="33">Level 33</option>
<option style="color:white;" value="34">Level 34</option>
<option style="color:white;" value="35">Level 35</option>
<option style="color:white;" value="36">Level 36</option>
<option style="color:white;" value="37">Level 37</option>
<option style="color:white;" value="38">Level 38</option>
<option style="color:white;" value="39">Level 39</option>
<option style="color:white;" value="40">Level 40</option>
<option style="color:white;" value="41">Level 41</option>
<option style="color:white;" value="42">Level 42</option>
<option style="color:white;" value="43">Level 43</option>
<option style="color:white;" value="44">Level 44</option>
<option style="color:white;" value="45">Level 45</option>
<option style="color:white;" value="46">Level 46</option>
<option style="color:white;" value="47">Level 47</option>
<option style="color:white;" value="48">Level 48</option>
<option style="color:white;" value="49">Level 49</option>
<option style="color:white;" value="50">Level 50</option>
<option style="color:white;" value="51">Level 51</option>
<option style="color:white;" value="52">Level 52</option>
<option style="color:white;" value="53">Level 53</option>
<option style="color:white;" value="54">Level 54</option>
<option style="color:white;" value="55">Level 55</option>
<option style="color:white;" value="56">Level 56</option>
<option style="color:white;" value="57">Level 57</option>
<option style="color:white;" value="58">Level 58</option>
<option style="color:white;" value="59">Level 59</option>
<option style="color:white;" value="60">Level 60</option>
<option style="color:white;" value="61">Level 61</option>
<option style="color:white;" value="62">Level 62</option>
<option style="color:white;" value="63">Level 63</option>
<option style="color:white;" value="64">Level 64</option>
<option style="color:white;" value="65">Level 65</option>
<option style="color:white;" value="66">Level 66</option>
<option style="color:white;" value="67">Level 67</option>
<option style="color:white;" value="68">Level 68</option>
<option style="color:white;" value="69">Level 69</option>
<option style="color:white;" value="70">Level 70</option>
<option style="color:white;" value="71">Level 71</option>
<option style="color:white;" value="72">Level 72</option>
<option style="color:white;" value="73">Level 73</option>
<option style="color:white;" value="74">Level 74</option>
<option style="color:white;" value="75">Level 75</option>
<option style="color:white;" value="76">Level 76</option>
<option style="color:white;" value="77">Level 77</option>
<option style="color:white;" value="78">Level 78</option>
<option style="color:white;" value="79">Level 79</option>
<option style="color:white;" value="80">Level 80</option>
<option style="color:white;" value="81">Level 81</option>
<option style="color:white;" value="82">Level 82</option>
<option style="color:white;" value="83">Level 83</option>
<option style="color:white;" value="84">Level 84</option>
<option style="color:white;" value="85">Level 85</option>
<option style="color:white;" value="86">Level 86</option>
<option style="color:white;" value="87">Level 87</option>
<option style="color:white;" value="88">Level 88</option>
<option style="color:white;" value="89">Level 89</option>
<option style="color:white;" value="90">Level 90</option>
<option style="color:white;" value="91">Level 91</option>
<option style="color:white;" value="92">Level 92</option>
<option style="color:white;" value="93">Level 93</option>
<option style="color:white;" value="94">Level 94</option>
<option style="color:white;" value="95">Level 95</option>
<option style="color:white;" value="96">Level 96</option>
<option style="color:white;" value="97">Level 97</option>
<option style="color:white;" value="98">Level 98</option>
<option style="color:white;" value="99">Level 99</option>
<option style="color:white;" value="100">Level 100</option>